server:
  port: 8000

spring:
  application:
    name: gateway-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/

zuul:
  host:
    connect-timeout-mills: 5000000
    socket-timeout-mills: 50000000
  ignored-services: '*'
  routes:
    product-service:
      path: /product/**
      serviceId: product-service
      stripPrefix: false
    category-service:
      path: /category/**
      serviceId: category-service
      stripPrefix: false


management:
  endpoints:
    web:
      exposure:
        include=*:
