server:
  port: 9076

spring:
  application:
    name: zipkin-service
  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
