server:
  port: 8091

spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://192.168.0.103:5432/postgres
    username: postgres
    password: docker

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
management:
  endpoints:
    web:
      exposure:
        include=*: